import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from './blocks/navbar'
import Footer from './blocks/footer'
import Thestory from './blocks/thestory'

export default function About() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
          <Navbar />
          <div className={styles.hero_about}>
          <div className="container">
            <div className="row px-3 py-5">
              <div className="col-sm py-5">
                <h1>About Us</h1>
                <p>All the intro text here</p>
              </div>
              <div className="col">
                the other text
              </div>
              
            </div>
          </div>
        </div>
        <div className="container min-vh-100">
          <div className="row justify-content-between px-3">
            <div className="col-sm-6 py-5">
            <h2>Vision</h2>
            "Notice that sweetgreen's mission is positioned to align with your values — not just written as something the brand believes. We love the inclusive language used in its statement.The language lets us know the company is all about connecting its growing network of farmers growing healthy, local ingredients with us — the customer — because we're the ones who want more locally grown, healthy food options.The mission to connect people is what makes this statement so strong. And, that promise has gone beyond sweetgreen's website and walls of its food shops: The team has made strides in the communities where it's opened stores as well. Primarily, it provides education to young kids on healthy eating, fitness, sustainability, and where food comes from." https://blog.hubspot.com/marketing/inspiring-company-mission-statements
            </div>
            <div className="col-sm-6 py-5">
            <h2>Mission</h2>
            "Patagonia's mission statement spotlights the company’s commitment to help the environment and save the earth. The people behind the brand believe that among the most direct ways to limit ecological impacts is with goods that last for generations or can be recycled so the materials in them remain in use.In the name of this cause, the company donates time, services, and at least 1% of its sales to hundreds of environmental groups worldwide.If your company has a similar focus on growing your business and giving back, think about talking about both the benefit you bring to customers and the value you want to bring to a greater cause in your mission statement." https://blog.hubspot.com/marketing/inspiring-company-mission-statements
            </div>
          </div>
          <div className="container">
            <div className="row justify-content-start">
              <div className="col-sm-10 ">
                <h2>Our Team</h2>
                  <div className="text-white">
                    "Patagonia's mission statement spotlights the   company’s commitment to help the environment and save the earth. The people behind the brand believe that among the most direct ways to limit ecological impacts is with goods that last for generations or can be recycled so the materials in them remain in use.In the name of this cause, the company donates time, services,
                  </div>
              </div>
              
            </div>
          </div>
          <div className="row justify-content-between px-2 py-5 m-auto">
            <div className="col-sm rounded p-2 bg-black m-2">
              <img src="/nft-1.jpg" width="100%" height="auto"/>
              <h3>CEO</h3>
              <div className="text-white">Some writting goes here if only you could learn how to type.</div>
              <div className="row my-3">
                <div className="col-1 me-2">
                  <a href="https://github.com/ahzu"><i className="bi bi-github fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://facebook.com/ahzudirecttech"><i className="bi bi-facebook fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://facebook.com/ahzudirecttech"><i className="bi bi-twitter fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://instagram.com/ahzu_direct_tech_llc"><i className="bi bi-instagram fs-1 text-white"></i></a>
                </div>
              </div>
            </div>
            <div className="col-sm rounded p-2 bg-black m-2">
            <img src="/nft-2.jpg" width="100%" height="auto"/>
              <h3>CFO</h3>
              <div className="text-white">Some writting goes here if only you could learn how to type.</div>
              <div className="row my-3">
                <div className="col-1 me-2">
                  <a href="https://github.com/ahzu"><i className="bi bi-github fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://facebook.com/ahzudirecttech"><i className="bi bi-facebook fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://facebook.com/ahzudirecttech"><i className="bi bi-twitter fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://instagram.com/ahzu_direct_tech_llc"><i className="bi bi-instagram fs-1 text-white"></i></a>
                </div>
              </div>
            </div>
            <div className="col-sm rounded p-2 bg-black m-2">
            <img src="/nft-5.jpg" width="100%" height="auto"/>
              <h3>CTO</h3>
              <div className="text-white">Some writting goes here if only you could learn how to type.</div>
              <div className="row my-3">
                <div className="col-1 me-2">
                  <a href="https://github.com/ahzu"><i className="bi bi-github fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://facebook.com/ahzudirecttech"><i className="bi bi-facebook fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://facebook.com/ahzudirecttech"><i className="bi bi-twitter fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://instagram.com/ahzu_direct_tech_llc"><i className="bi bi-instagram fs-1 text-white"></i></a>
                </div>
              </div>
            </div>
            <div className="col-sm rounded p-4 bg-black m-2">
            <img src="/nft-4.jpg" width="100%" height="auto"/>
              <h3>COO</h3>
              <div className="text-white">Some writting goes here if only you could learn how to type.</div>
              <div className="row my-3">
                <div className="col-1 me-2">
                  <a href="https://github.com/ahzu"><i className="bi bi-github fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://facebook.com/ahzudirecttech"><i className="bi bi-facebook fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://facebook.com/ahzudirecttech"><i className="bi bi-twitter fs-1 text-white"></i></a>
                </div>
                  <div className="col-1 me-2"><a href="https://instagram.com/ahzu_direct_tech_llc"><i className="bi bi-instagram fs-1 text-white"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Thestory />
        <Footer />
    </div>
  )
}
