import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from './blocks/navbar'
import Footer from './blocks/footer'
import HeroFP from './blocks/hero-frontpage'
import FaqAccordian from './blocks/faq-accordian'

export default function FAQs() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
        <HeroFP />
        <FaqAccordian />


      <Footer />
    </div>
  )
}
